# Generated by Django 2.0.3 on 2018-03-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_auto_20180330_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='desciption',
            new_name='description',
        ),
    ]
